#+TITLE: 2021 年终回顾
#+DATE: 2021-12-31T18:20:27+08:00
#+DRAFT: false
#+TAGS[]: review

Time Flies！

* 回顾
EmacsTalk 在 2021-06-26 上线，到现在已经半年了，元旦将至，是时候做个年终回顾了。先看看这半年的数据吧：
- 播客：9 期
- 技巧文章：13 期
- 网站 PV：13450
- 网站 UV：10758
- 公众号订阅数：866
- 发电赞助： ¥500（由衷感谢这些发电的热心听众）

#+CAPTION: 百度统计 07/01-12/31
https://img.alicdn.com/imgextra/i3/581166664/O1CN01SDbLcu1z6A7Hdeh1g_!!581166664.png

在节目一开始，主要是进行播客的制作，一方面是新奇，热情高涨，另一方面是知道随着时间的推进，节目的节奏肯定会慢下来，因此想一开始多制作几期，让大家对这个播客有些了解，算是在市场站住脚。

最快的时候当天录制，第二天就剪辑发布出来了。时长一小时的播客，制作时间一般需要 3-4 个小时，是个费事费力的事情。但是听播客就很快，我一般都是倍速听播客，而且一般听是在闲暇时间，所以更没有时间的概念。

在制作了 9 期后，正好赶上双十一，工作上的事会多些，因此就打算方式放松一段时间，然后就一直到现在。这期间一直在创作使用技巧的文章，Emacs 就是这么神奇，即使在使用了 5 年后，还是能不时发现新的用法。
** 数据分析
借助于百度、微信等平台，能大致看出 EmacsTalk 的听众的画像，觉得还比较有意思，这里和大家分享下。
*** 最受欢迎的嘉宾
#+ATTR_HTML: :border 1 :style text-align:center
| 排名 | 百度统计 | Google 统计 | 小宇宙 | 微信公众号 |
|------+----------+-------------+--------+------------|
|    1 | 领蜂     | 陈斌        | 陈斌   | Kathy      |
|    2 | 陈斌     | Kathy       | 领蜂   | 领蜂       |
|    3 | tumashu  | stardiviner | Kathy  | 陈斌       |

恭喜上述 TOP3 的嘉宾，但数据并不能代表一切，其他嘉宾的内容同样“湿货”满满，这里着重感谢所有嘉宾的鼎力支持。❤️️
#+CAPTION: 小宇宙信息统计
https://img.alicdn.com/imgextra/i1/581166664/O1CN01xAP4JM1z6A79huitw_!!581166664.jpg
*** 听众区域分布
#+CAPTION: 国内
https://img.alicdn.com/imgextra/i2/581166664/O1CN01I2obiY1z6A7Dv6h9p_!!581166664.png

#+CAPTION: 国外
https://img.alicdn.com/imgextra/i1/581166664/O1CN01QADkBR1z6A7FmQB7V_!!581166664.png

* 展望
在新一年，除了现有采访模式的播客，我还想再找一个主播，和我一起来讨论 Emacs 最近的一些动向，因为在订阅 emacs-devel 邮件列表后，发现里面有很多有意思的讨论。邮件列表的内容很容易被埋没，因此如果能有人能定期把里面有价值、有趣的内容分享出来，觉得会是件非常是意义的事，如果哪位听众、读者对这件事感兴趣，欢迎和我联系。

此外，如果能找到另一个主播，节目的更新频率也能得到更好地保证。

最后定个新年目标吧，希望 2022 年能完成
- 12 期播客节目
- 30 篇使用技巧的文章

祝各位读者、听众新年快乐，Make Emacs Great Again！
